### ISSUE TITLE
OpenFast crashes on Linux  munmap_chunk()

### ISSUE THREAD

**Issue by selvavm** [OpenFAST/openfast#209]
This is the first time I am using OpenFAST and today when I downloaded it from master and try with 18, I get below error.
```
**************************************************************************************************
 OpenFAST

 Copyright (C)  National Renewable Energy Laboratory

 This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY.
 See the "LICENSE" file distributed with this software for details.
 **************************************************************************************************

 OpenFAST--128-NOTFOUND
 Compile Info:
  - Architecture: 64 bit
  - Precision: double
 Execution Info:
  - Date: 11/29/2018
  - Time: 17:26:25+0000

 OpenFAST input file heading:
     FAST Certification Test #18: NREL 5.0 MW Baseline Wind Turbine (Onshore)

 Running ElastoDyn.
 Running AeroDyn.
 Running AirfoilInfo.
 Running BEM.
 Running InflowWind.
*** Error in `openfast': munmap_chunk(): invalid pointer: 0x0000000002a6eb70 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7b184)[0x7fb3402ea184]
openfast[0xb67185]
openfast[0x513295]
openfast[0x62d6c4]
openfast[0x65003d]
openfast[0x4d99a2]
openfast[0x41392f]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fb340290b15]
openfast[0x413961]
======= Memory map: ========
00400000-019e1000 r-xp 00000000 00:2d 59840593866                        /ifs/home/seved/fast.farm/install/bin/openfast
01be0000-01be9000 r--p 015e0000 00:2d 59840593866                        /ifs/home/seved/fast.farm/install/bin/openfast
01be9000-01c56000 rw-p 015e9000 00:2d 59840593866                        /ifs/home/seved/fast.farm/install/bin/openfast
01c56000-01c9b000 rw-p 00000000 00:00 0
02983000-02ac6000 rw-p 00000000 00:00 0                                  [heap]
7fb34026f000-7fb340425000 r-xp 00000000 fd:00 1074696787                 /usr/lib64/libc-2.17.so
7fb340425000-7fb340625000 ---p 001b6000 fd:00 1074696787                 /usr/lib64/libc-2.17.so
7fb340625000-7fb340629000 r--p 001b6000 fd:00 1074696787                 /usr/lib64/libc-2.17.so
7fb340629000-7fb34062b000 rw-p 001ba000 fd:00 1074696787                 /usr/lib64/libc-2.17.so
7fb34062b000-7fb340630000 rw-p 00000000 00:00 0
7fb340630000-7fb34066e000 r-xp 00000000 00:2f 33849290906                /ifs/opt/app/gcc/7.3.0/lib64/libquadmath.so.0.0.0
7fb34066e000-7fb34086d000 ---p 0003e000 00:2f 33849290906                /ifs/opt/app/gcc/7.3.0/lib64/libquadmath.so.0.0.0
7fb34086d000-7fb34086e000 r--p 0003d000 00:2f 33849290906                /ifs/opt/app/gcc/7.3.0/lib64/libquadmath.so.0.0.0
7fb34086e000-7fb34086f000 rw-p 0003e000 00:2f 33849290906                /ifs/opt/app/gcc/7.3.0/lib64/libquadmath.so.0.0.0
7fb34086f000-7fb340885000 r-xp 00000000 00:2f 33633263594                /ifs/opt/app/gcc/7.3.0/lib64/libgcc_s.so.1
7fb340885000-7fb340a84000 ---p 00016000 00:2f 33633263594                /ifs/opt/app/gcc/7.3.0/lib64/libgcc_s.so.1
7fb340a84000-7fb340a85000 r--p 00015000 00:2f 33633263594                /ifs/opt/app/gcc/7.3.0/lib64/libgcc_s.so.1
7fb340a85000-7fb340a86000 rw-p 00016000 00:2f 33633263594                /ifs/opt/app/gcc/7.3.0/lib64/libgcc_s.so.1
7fb340a86000-7fb340b87000 r-xp 00000000 fd:00 1074696795                 /usr/lib64/libm-2.17.so
7fb340b87000-7fb340d86000 ---p 00101000 fd:00 1074696795                 /usr/lib64/libm-2.17.so
7fb340d86000-7fb340d87000 r--p 00100000 fd:00 1074696795                 /usr/lib64/libm-2.17.so
7fb340d87000-7fb340d88000 rw-p 00101000 fd:00 1074696795                 /usr/lib64/libm-2.17.so
7fb340d88000-7fb340f59000 r-xp 00000000 00:2f 33847262990                /ifs/opt/app/gcc/7.3.0/lib64/libgfortran.so.4.0.0
7fb340f59000-7fb341159000 ---p 001d1000 00:2f 33847262990                /ifs/opt/app/gcc/7.3.0/lib64/libgfortran.so.4.0.0
7fb341159000-7fb34115a000 r--p 001d1000 00:2f 33847262990                /ifs/opt/app/gcc/7.3.0/lib64/libgfortran.so.4.0.0
7fb34115a000-7fb34115b000 rw-p 001d2000 00:2f 33847262990                /ifs/opt/app/gcc/7.3.0/lib64/libgfortran.so.4.0.0
7fb34115b000-7fb34115c000 rw-p 00000000 00:00 0
7fb34115c000-7fb3412d1000 r-xp 00000000 00:2f 33838029237                /ifs/opt/app/gcc/7.3.0/lib64/libstdc++.so.6.0.24
7fb3412d1000-7fb3414d1000 ---p 00175000 00:2f 33838029237                /ifs/opt/app/gcc/7.3.0/lib64/libstdc++.so.6.0.24
7fb3414d1000-7fb3414db000 r--p 00175000 00:2f 33838029237                /ifs/opt/app/gcc/7.3.0/lib64/libstdc++.so.6.0.24
7fb3414db000-7fb3414dd000 rw-p 0017f000 00:2f 33838029237                /ifs/opt/app/gcc/7.3.0/lib64/libstdc++.so.6.0.24
7fb3414dd000-7fb3414e1000 rw-p 00000000 00:00 0
7fb3414e1000-7fb3414e4000 r-xp 00000000 fd:00 1074696793                 /usr/lib64/libdl-2.17.so
7fb3414e4000-7fb3416e3000 ---p 00003000 fd:00 1074696793                 /usr/lib64/libdl-2.17.so
7fb3416e3000-7fb3416e4000 r--p 00002000 fd:00 1074696793                 /usr/lib64/libdl-2.17.so
7fb3416e4000-7fb3416e5000 rw-p 00003000 fd:00 1074696793                 /usr/lib64/libdl-2.17.so
7fb3416e5000-7fb341734000 r-xp 00000000 00:2d 59744747052                /ifs/home/seved/vts.farm/install/lib64/libblas.so.3.6.0
7fb341734000-7fb341933000 ---p 0004f000 00:2d 59744747052                /ifs/home/seved/vts.farm/install/lib64/libblas.so.3.6.0
7fb341933000-7fb341934000 r--p 0004e000 00:2d 59744747052                /ifs/home/seved/vts.farm/install/lib64/libblas.so.3.6.0
7fb341934000-7fb341935000 rw-p 0004f000 00:2d 59744747052                /ifs/home/seved/vts.farm/install/lib64/libblas.so.3.6.0
7fb341935000-7fb341ef5000 r-xp 00000000 00:2d 59744747053                /ifs/home/seved/vts.farm/install/lib64/liblapack.so.3.6.0
7fb341ef5000-7fb3420f4000 ---p 005c0000 00:2d 59744747053                /ifs/home/seved/vts.farm/install/lib64/liblapack.so.3.6.0
7fb3420f4000-7fb3420f5000 r--p 005bf000 00:2d 59744747053                /ifs/home/seved/vts.farm/install/lib64/liblapack.so.3.6.0
7fb3420f5000-7fb3420f8000 rw-p 005c0000 00:2d 59744747053                /ifs/home/seved/vts.farm/install/lib64/liblapack.so.3.6.0
7fb3420f8000-7fb342143000 rw-p 00000000 00:00 0
7fb342143000-7fb342164000 r-xp 00000000 fd:00 1074696780                 /usr/lib64/ld-2.17.so
7fb342337000-7fb34233e000 rw-p 00000000 00:00 0
7fb342361000-7fb342364000 rw-p 00000000 00:00 0
7fb342364000-7fb342365000 r--p 00021000 fd:00 1074696780                 /usr/lib64/ld-2.17.so
7fb342365000-7fb342366000 rw-p 00022000 fd:00 1074696780                 /usr/lib64/ld-2.17.so
7fb342366000-7fb342367000 rw-p 00000000 00:00 0
7ffd97cae000-7ffd97dbf000 rw-p 00000000 00:00 0                          [stack]
7ffd97ded000-7ffd97def000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7fb3402a466f in ???
#1  0x7fb3402a45f7 in ???
#2  0x7fb3402a5ce7 in ???
#3  0x7fb3402e4316 in ???
#4  0x7fb3402ea183 in ???
#5  0xb67184 in ???
#6  0x513294 in ???
#7  0x62d6c3 in ???
#8  0x65003c in ???
#9  0x4d99a1 in ???
#10  0x41392e in ???
#11  0x7fb340290b14 in ???
#12  0x413960 in ???
#13  0xffffffffffffffff in ???
Aborted
```

**Comment by rafmudaf** [comment]
@selvavm Can you give me some specifics on your system like compiler version and OS type and version? Also, did you download this from the master or dev branch?

**Comment by selvavm** [comment]
Hi - Sorry, I could see that you have fixed this in the dev branch.
